### ISSUE TITLE
Excluding attributes

### ISSUE THREAD

**Issue by luke-j** [almost-full-stack/sequelize-graphql-schema#15]
Hi - thanks for the package, very helpful!

It doesn't seem like the `model.attributes.exclude` option is implemented? Is there another way to exclude an attribute from a graphql type?

**Comment by alirizwan** [comment]
that would be strange since i am using this feature in production, I will still re-check this. But the way attributes are excluded might change after merging PR#12

**Comment by Yehonal** [comment]
could you check it again @luke-j ? it should be fixed
