### ISSUE TITLE
Support custom documentation on models and fields

### ISSUE THREAD

**Issue by peterviergutz** [almost-full-stack/sequelize-graphql-schema#17]
First of all: thank you for your efforts in keeping this project alive 👍 

I'm having more a question than an issue - do you have any plans to support customized documentation on models and/or model fields? Thinking in the direction of

```js
const MyModel = orm.db.define('my_model', {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true,
        description: "My very custom description of this field" // <- use this in the field's GraphQLType
    },
    anotherField: {
        type: Sequelize.STRING,
        description: "Another an even weirder description, maybe with an example value in markdown `FOO` or `bar_123`" // <- use this in the field's GraphQLType
    }
}, 
{
    description: "The MyModel type represents my model and I really want to tell you something about it." // <- use this in the model's GraphQLType
})
```

or - if adding custom fields to the model itself is not so desirable - for example

```
const MyModel.graphql = {
    modelDescription: "...",
    fieldDescriptions: {
        id: ""
    }
}
```

or maybe (also) supporting converting comments from DB fields to descriptions, like already being supported in graphql-sequelize.

I'd be happy to contribute, let me know what you think. 

Cheers!

**Comment by alirizwan** [comment]
Please do contribute. I have a huge backlog for myself as well and can really use some contributors to make it more than just a CRUD library. I would recommend adding custom fields in model description as well as have an option to add fieldDescription for those fields which are handled by sequelize itself such as id, foreignkeys etc. Description for those could be added in fieldDescription or in model. Both options would be awesome.

**Comment by alirizwan** [comment]
This is now supported. `1.0.0-beta.8`
