### ISSUE TITLE
Creating association records via single mutation 

### ISSUE THREAD

**Issue by RenatoFranze** [almost-full-stack/sequelize-graphql-schema#32]
Hi,

This is not an "issue question" but more likely a "how to", hehe.

I was reading the closed issues and saw this one (https://github.com/almost-full-stack/sequelize-graphql-schema/issues/4)

So, it is possible to create, within a single mutation, related rows in the db, like creating a new user and a new post associated to that user, right? 

If so, what do I need to do with my sequelize models or with the config of this lib to get this working? 

Thanks!

**Comment by alirizwan** [comment]
This indeed is possible if you use `1.0.0-beta.0`

**Comment by RenatoFranze** [comment]
Oh, nice!

I'll add the beta version and try for myself. Is there any plan about when it will be released as a stable version? 

Thanks!

**Comment by alirizwan** [comment]
working on the stable version, not getting a lot of time these days but probably in 1-2 weeks.

**Comment by RenatoFranze** [comment]
Hi Ali, 

After switching to the beta version, I'm getting the error:

![image](https://user-images.githubusercontent.com/10964864/65282788-2ba78480-db0c-11e9-8ba4-e1907613054d.png)

Following the error link, it goes to this line in dist/sequelize-graphql-schema.js: 

buildAssoc(assocModel, reference, 'BelongsTo', reference.name || reference.as, true);

Do you know what this could be?

**Comment by Yehonal** [comment]
I have a fix for it. Will be released soon

Il gio 19 set 2019, 23:37 RenatoFranze <notifications@github.com> ha
scritto:

**Comment by RenatoFranze** [comment]
Thanks @Yehonal , 

I'll be looking forward for the fix.

**Comment by Yehonal** [comment]
Fix in this PR: https://github.com/almost-full-stack/sequelize-graphql-schema/pull/34 i've implemented join queries too

**Comment by RenatoFranze** [comment]
Hi @Yehonal , is this fix available for testing?

**Comment by alirizwan** [comment]
Hi, this fix will be published tomorrow and you can then test it.

**Comment by RenatoFranze** [comment]
Hi there, 

Any news?

**Comment by alirizwan** [comment]
publishing today, have some conflicts to be resolved.

**Comment by alirizwan** [comment]
@RenatoFranze hi please use `1.0.0-beta.8` it has tons of new features and optimizations including association creation/updation.
