### ISSUE TITLE
Custom nested type is assumed to be Sequelize model, query overrides requested return values

### ISSUE THREAD

**Issue by charlie-s** [almost-full-stack/sequelize-graphql-schema#33]
Given these custom GraphQL types that are generated dynamically in my resolver:

```
Widget.graphql.types.order = {
    number: 'string!',
    jobs: '[orderJob]'
};

Widget.graphql.types.orderJob = {
    type: 'string!',
};
```

I receive the following error when I attempt to query for a job:

> Cannot query field \"jobs\" on type \"order\".

It seems that it assumed `jobs` is a Sequelize association and tries to handle it that way. Is that correct? How can I handle nested custom types?

Thanks for any info you can share.

**Comment by alirizwan** [comment]
is it possible for you to share your widget model? custom types does support nested CUSTOM types. There's only one way this can break is if your custom type name matches with a model name, in that case model type would override custom type.

**Comment by charlie-s** [comment]
You're so responsive, it's greatly appreciated! Here's full code:

```
Contractor.graphql.types.contractorJobsInput = {
    statusAccepted: 'boolean!',
    statusShipped: 'boolean!',
};

Contractor.graphql.types.contractorJob = {
    poNumber: 'string',
    number: 'string!',
    designs: '[contractorJobDesign]'
};

Contractor.graphql.types.contractorJobDesign = {
    id: 'number!',
    name: 'string!',
};

Contractor.graphql.queries.contractorJobs = {
    input: 'contractorJobsInput!',
    output: '[contractorJob]!',
    resolver: async (source, input, ctx, info) => {
        ...
```

I do have a Sequelize model called `Design` but not `designs`. I've also tried other names, but whenever I attempt to include these fields I receive that same error. Here's my query:

```
query {
  contractorJobs(contractorJobsInput: {
    statusAccepted: true
    statusShipped: false
  }) {
    number
    poNumber
    designs {
      name
    }
  }
}
```

**Comment by alirizwan** [comment]
Your implementation seems correct, maybe problem is somewhere else. The query you shared doesn't include `jobs` key and the error you are getting is regarding `jobs`. I m not sure if I can find the root cause here. Can you please share a screenshot of your generated schema?

**Comment by charlie-s** [comment]
Sorry, the first code sample was pseudo. With what I posted, I get:

>Cannot query field "designs" on type "contractorJob".

**Comment by alirizwan** [comment]
I am going to reproduce this issue on my side and get back to you.

**Comment by alirizwan** [comment]
Charlie, a really tiny issue with the naming, `Contractor.graphql.types.contractorJob = {
    poNumber: 'string',
    number: 'string!',
    designs: '[contractorJobDesign]'
};`

You see the Type you are referring to here is contractorJobDesign and even though your key name is designs its renamed to actual Type name, so if you take a look at the schema it's like this:`poNumber: String
number: String!
contractorJobDesign: [contractorJobDesign]`

So if you query: ```query {
  contractorJobs(contractorJobsInput: {
    statusAccepted: true
    statusShipped: false
  }) {
    number
    poNumber
    contractorJobDesign {
      name
    }
  }
}``` it would work.

**Comment by alirizwan** [comment]
The new update coming would fix this issue, meanwhile I would recommend to use same name for key and type.

**Comment by charlie-s** [comment]
That works! Thanks Ali. Look forward to the update.
