### ISSUE TITLE
SQL Where conditions in Edit mutation

### ISSUE THREAD

**Issue by RenatoFranze** [almost-full-stack/sequelize-graphql-schema#35]
Hi guys, 

I can't find anyway to pass a where condition in the auto generated edit mutation. The documentation only shows a input type argument, where I belive is for the fields I wanna change, but how to do this operation only on the rows I want to?

Thanks!

**Comment by Yehonal** [comment]
you cannot edit/delete with a where for now, it can be a security breach hard to handle with an ACL/authorization system (but not impossible). You can currently use bulk edit and bulk update alternatively.

However, i'm using an internal developed ACL system that would work with a "where", so we can enable this feature with an option. What do you think @alirizwan?

**Comment by alirizwan** [comment]
It definitely can be a future feature, but in update you don’t pass a custom where clause (security hazard) however when you send input you are also sending id in it which is then used to construct where clause internally. So for example you have this input {id:2, name: “test”} id being the pk. This will be translated internally into this:
Model.update(input, {where:{id:2}});
However if you want to update or delete in bulk you must use bulk operations as yehonal suggested.

Sent from my iPhone

On Oct 4, 2019, at 4:43 PM, Yehonal <notifications@github.com> wrote:

﻿

you cannot edit/delete with a where for now, it can be a security breach hard to handle with an ACL/authorization system (but not impossible). You can currently use bulk edit and bulk update alternatively.

However, i'm using an internal developed ACL system that would work with a "where", so we can enable this feature with an option. What do you think @alirizwan<https://github.com/alirizwan>?

**Comment by RenatoFranze** [comment]
> It definitely can be a future feature, but in update you don’t pass a custom where clause (security hazard) however when you send input you are also sending id in it which is then used to construct where clause internally. So for example you have this input {id:2, name: “test”} id being the pk. This will be translated internally into this: Model.update(input, {where:{id:2}}); However if you want to update or delete in bulk you must use bulk operations as yehonal suggested.

Thanks for the reply, @Yehonal  and @alirizwan ,

I tought that using the primary key in the input would update all rows, lol.

So, the best way is to do a query with my where condition, get all the primary keys that a I want to update and make a bulk edit mutation, right? I'm asking this because I enabled bulk edit in my model and the documentation for the bulk method don't show a where argument, only an array of input type.

**Comment by alirizwan** [comment]
Yes, that's the best way to do it and it will make sure data integrity is maintained.
________________________________

**Comment by RenatoFranze** [comment]
Perfect, guys! 

Thanks very much!
